config/routes.rb
Rails.application.routes.draw do
  #resources :users
  devise_for :users

  resources :events

  resources :listings
  #get 'listings/welcome', controller: 'listings', action: 'welcome'

  resources :investors, controller: 'users', user_type: 'Investor'
  resources :managers, controller: 'users', user_type: 'Manager'
  resources :realtors, controller: 'users', user_type: 'Realtor'

  get 'about_us', controller: 'pages'
  get 'faq', controller: 'pages'

  root 'pages#index'

  
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :realtor
  has_one :manager
  has_many :investors
  has_many :events  

  has_attached_file :avatar
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @listing=Listing.find(params[:id])
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params[:listing]
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<link href='/css/general_listings' rel='stylesheet'>
<h1>Listing listings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <div class = 'col-md-3 thumbnail my-thumbnails'>
          <div class='col-md-12'>
            <img class = 'listing-image' src="<%= listing.avatar %>" %>
            <h4 class='listing-price'><%= number_to_currency(listing.price) %></h4>
          </div>
          <div class='col-md-12 listing-info'>
            <p><%= listing.address %></p>
            <p><%= listing.city %></p>
            <p><%= listing.state %></p>
            <p><%= listing.zip_code %></p>
            <a class='btn btn-primary' href='listings/:id'>See More</a>
          </div>
          <div class='col-md-12 listing-info'>
            <td><%= link_to 'Show', listing %></td>
            <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
            <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </div>
        </div>
      </tr>

    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>



<!-- <div class = 'thumbnail col-md-3 my-thumbnails'>
  <div class='col-md-12'>
      <img class='listing-image' src="http://lorempixel.com/200/100/sports">
      <h4 style="color: #000; text-align: center; margin-top: 10%">$1000</h4>
  </div>
  <div class='col-md-12 listing-info'>
      <p>123 Main St</p>
      <p>Apt 5A</p>
      <p>Anywhere, NY 01234</p>       
  </div>
</div> -->

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<div class = 'col-md-3 thumbnail my-thumbnails'>
  <div class='col-md-12'>
    <img class = 'listing-image' src="<%= listing.avatar %>">
    <h4 class='listing-price'>$<%= listing.price %></h4>
  </div>
  <div class='col-md-12 listing-info'>
    <p><%= listing.address %></p>
    <p><%= listing.city %></p>
    <p><%= listing.state %></p>
    <p><%= listing.zip_code %></p>
  </div>
  <div class='col-md-12 listing-info'>
    <td><%= link_to 'Show', listing %></td>
    <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
    <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </div>
</div>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>